
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"daniel-upgrade","number":12,"title":"Upgrading Backend to Spring-Boot 3.2.5","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/12"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-ExposeCommit","number":10,"title":"Pull Request for TA and Prof assistance (Expose Commit Information)","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/10"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-Swagger","number":7,"title":"Added Option to Enable/Disable Swagger on Navbar","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/7"}]
