
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-courseImprovements","number":47,"title":"Refactor Courses to link to a backend school [NON-ASSIGNED]","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/47"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-SchoolsCRUD-UIImprovements","number":46,"title":"School Page UI Improvements","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/46"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-SchoolsCRUD-BackendBugs","number":45,"title":"School Edit Page now prevents user from editing the Abbrev param","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/45"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-roster-courseShow","number":43,"title":"Refactor CourseShowPage to include StudentForm","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/43"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-StaffCreatePage","number":36,"title":"Jason Staff Create Page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/36"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-SchoolsCRUD-Delete","number":35,"title":"Schools Delete Button","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/35"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-SchoolsCRUD-Edit","number":31,"title":"Schools Edit Page and tests, + Minor CreatePageTest error fixed","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/pull/31"}]
